server:
  port: 8780

spring:
  application:
    name: spring-playground-boot
  jpa.hibernate.ddl-auto: none
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
          lob.non_contextual_creation: true
          order_inserts: true
        format_sql: true
        show_sql: true

logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
