spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS LOZM
    username: laonzenamoon
    password: laonzenamoon
    testQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
