spring:
  application:
    name: default-spring-batch
  jpa.hibernate.ddl-auto: none
  profiles:
    active: local
  batch.job.names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
          lob.non_contextual_creation: true
          order_inserts: true
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    root: info
    me.lozm: debug
