spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lozm
    username: junlee
    password: password
    testQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

decorator:
  datasource:
    p6spy:
      enable-logging: true
